### ISSUE TITLE
Mention background color invalid when using default hex colors

### ISSUE THREAD

**Issue by Jozh-POST** [DevEvil99/DarkPlus-Discord-Theme#2]
I'm assuming the mention background is supposed to be colored and visible, but it's not for me. Can hex be used in `rgba()` on specific platforms that I'm not using? The issue resolves itself converting the hex values to RGB.

```css
:root {
  --darkplus-sec: #bb86fc;
}
.mentioned-xhSam7 {
  background-color: rgba(var(--darkplus-sec), 0.1) !important;
}
.mentioned-xhSam7:hover {
  background-color: rgba(var(--darkplus-sec), 0.2) !important;
}
```

**Comment by DevEvil99** [comment]
mention background is colored and visible and if you want change that download "Theme Settings" plugin

**Comment by Jozh-POST** [comment]
I do use the `Theme Setting` plugin already. Even in the in-app `Theme Repo` plugin, if you use the preview tool, you can see that the background of a mention is still the same color as the normal background. The only addition is the colored side-bar of the mention.

![8Q8gEjRaOuxoIAbmMH6h](https://user-images.githubusercontent.com/58705200/148717962-508c6088-42f2-404d-b080-bd05c91c4043.png)

**Comment by DevEvil99** [comment]
You are mentioning a role 
![Screenshot 2022-01-10 094007](https://user-images.githubusercontent.com/73029696/148724538-1920199d-ae27-42eb-9a65-5608cfdc95e5.png)
![Screenshot 2022-01-10 094031](https://user-images.githubusercontent.com/73029696/148724541-366538ea-20d0-4dbf-8f8c-75ed519ec241.png)

**Comment by Jozh-POST** [comment]
What I'm talking about is the change in the entire message background when *you* are mentioned, not the mention itself. The lines I listed in my first post from https://devevil99.github.io/devevil/BetterDiscordAddons/Theme/Dark+/Dark+.theme.css
are not actually doing anything because the hex is used when trying to use `rgba()`. As a visual example, here's how it would look like if you provide the rgb components of `--darkplus-sec` manually to `rgba()`.
```css
/* #bb86fc = (187, 134, 252) */
.mentioned-xhSam7 {
  background-color: rgba(187, 134, 252, 0.1) !important;
}
.mentioned-xhSam7:hover {
  background-color: rgba(187, 134, 252, 0.2) !important;
}
```

![v2M5Hkx0ABZTTlYClfWg](https://user-images.githubusercontent.com/58705200/148725443-40733773-5123-45c6-910f-3a2302a9823d.png)
