### ISSUE TITLE
Fix for a memberlist issue

### ISSUE THREAD

**Issue by fowlis** [DevEvil99/DarkPlus-Discord-Theme#3]
Wasn't me that found it, but I'm posting for another user who had the issue, in smaller servers the member list's background cuts off

![](https://media.discordapp.net/attachments/126228856477712384/951220264992137346/unknown.png)

```css
.container-2o3qEW {background-color:rgb(33, 33, 33)}
```
This code will fix it, I would have done a PR but I don't really know how 😅
